server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wblog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 20000821w
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 192.168.126.131
    port: 6379
    password: 20000821w
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: ${ALIYUN_OSS_KEY_ID}
      keysecret: ${ALIYUN_OSS_KEY_SECRET}
      bucketname: education-010101
